### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by Gibbsdavidl** [jingshuw/descend#1]
Hi there,

Nice package, thank you.  The value returned by the runDescend function needs much much more documentation!  Also ?DESCEND.  Actually, a short vignette of how to work with the results of the package would be invaluable.

Given  res <- runDescend(...)
In res@distribution:  What are theta, g, SE.g, G, etc.

Thank you!

PS:  Is the library size necessary?

**Comment by jingshuw** [comment]
Thanks for using the package! I have just added more interpretations of the S4 class DESCEND (check it by help(DESCEND)), including an explanation of res@distribution. 

We need either the Library size or cell size to make the noise model correct (see more details from our paper). If scaling.consts = NULL (by Default), then DESCEND will use the sum across all rows in count.matrix for each column as library size. 

I will consider writing a tutorial in the future, but you can check how DESCEND is used in our paper for different case studies in jingshuw/DESCEND_manuscript_source_code
